# 1. Force HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# Redirect WWW to apex
[[redirects]]
  from = "https://www.ambitrove.com/*"
  to = "https://ambitrove.com/:splat"
  status = 301
  force = true

# 3. SPA fallback for Vite/React
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200